### ISSUE TITLE
spring-integration-aws: spring-integration-core version is not updated

### ISSUE THREAD

**Issue by sowdri** [spring-projects/spring-integration-extensions#119]
In build.gradle file the spring-integration version is found to be 

`springIntegrationVersion = '4.0.3.RELEASE'`

But while including it from maven central, the published version still depends on older version of spring integration.

 	<groupId>org.springframework.integration</groupId>
	<artifactId>spring-integration-aws</artifactId>
	<version>0.5.0.RELEASE</version>
	<name>Spring Integration AWS Support</name>

	    <dependency>
	      <groupId>org.springframework.integration</groupId>
	      <artifactId>spring-integration-mail</artifactId>
	      <version>2.2.2.RELEASE</version>
	      <scope>compile</scope>
	      <optional>true</optional>
	    </dependency>
	    <dependency>
	      <groupId>org.springframework.integration</groupId>
	      <artifactId>spring-integration-core</artifactId>
	      <version>2.2.2.RELEASE</version>
	      <scope>compile</scope>
	    </dependency>

While the latest commit message says that the spring integration has been updated to use `4.0.3.RELEASE`.

Because of this I'm also getting the following error:
`Caused by: java.lang.ClassNotFoundException: org.springframework.integration.Message`

I'm guessing the version published to Maven Central could be an older version. In that case, could you kindly republish it again. 

Thanks for the wonderful work.

**Comment by artembilan** [comment]
The Spring Integration AWS project has been moved to separate repository (https://github.com/spring-projects/spring-integration-aws) and now it is fully based on the Spring Integration `4.1.x`.
