### ISSUE TITLE
Spring integration kafka.

### ISSUE THREAD

**Issue by rahulmaindargi** [spring-projects/spring-integration-extensions#125]
The XSD not present at below location.
http://www.springframework.org/schema/integration/kafka/spring-integration-kafka.xsd

Even kafka folder itself is missing from http://www.springframework.org/schema/integration/

The project last updated 3 months ago

**Comment by artembilan** [comment]
The Spring Integration Kafka 1.1 has been released recently: https://spring.io/blog/2015/03/26/spring-integration-kafka-support-1-1-ga-is-available
So, looks like http://www.springframework.org/schema/integration/kafka/spring-integration-kafka.xsd works well.
