### ISSUE TITLE
Please publish spring-integration-zip 1.0.0.M1

### ISSUE THREAD

**Issue by fossamagna** [spring-projects/spring-integration-extensions#153]
First thanks for "Spring Integration Zip Support". I would like to use it within my project, but I can't downlaod artifact of spring-integration-zip from [Spring Framework Maven Milestone Repository](https://repo.spring.io/libs-milestone/).  Would you publish 1.0.0.M1?

**Comment by artembilan** [comment]
Hello, @fossamagna !

First of all thank you for the attention to the project!

If you can confirm that everything here works well for you and when I am sure from my side that project looks well, I'll be able to release M1 this week exactly before Christmas.
Maybe even today...

**Comment by fossamagna** [comment]
@artembilan Thank you! It's a great help.

**Comment by robmoore** [comment]
Just curious if this was published. I'd like to use it as well.

**Comment by artembilan** [comment]
Oh! This long New Years holidays has clear the memory :smile: 
Thank you reminder!

Let me check what's going on there just right now!

**Comment by artembilan** [comment]
So, I've just done some "hard" polishing there https://github.com/spring-projects/spring-integration-extensions/commit/0a5fedcd7a67f9cc36f99a1dc9fa06c300f0b787.
We have a "green" build on the matter https://build.spring.io/browse/INTEXT-ZIP-7
And it even passes for me on Windows.

I'll take a look to this in the morning and hope there won't be any obstacles do not release it tomorrow.

**Comment by robmoore** [comment]
Wow, thanks for the swift action. I'll keep my fingers crossed.

**Comment by artembilan** [comment]
OK, guys!

I'm consider the work as finished and `spring-integration-zip-1.0.0.M1` has been released: http://repo.spring.io/libs-milestone/org/springframework/integration/spring-integration-zip/1.0.0.M1/.

Congratulations to all and I'd be glad to hear some feedback how to go ahead with this extension.
Any way to communication is workable.

**Comment by robmoore** [comment]
Thanks @artembilan !

**Comment by fossamagna** [comment]
@artembilan Thank you very match!
