### ISSUE TITLE
zip extension with DSL

### ISSUE THREAD

**Issue by robmoore** [spring-projects/spring-integration-extensions#155]
I'm trying to use the milestone build of the zip integration and am not having any success with the unzip result splitter flow I've created using [one of the tests](https://github.com/spring-projects/spring-integration-extensions/blob/master/spring-integration-zip/src/test/java/org/springframework/integration/zip/UnZip2FileTests-context.xml) in the repo. 

Here is my interpretation of the configuration:
```
   @Bean
   public IntegrationFlow fileWritingFlow() {
        return IntegrationFlows.from(unzipInboundResultChannel()).wireTap(f -> f.handle(logger()))
                .handle(Files.outboundAdapter("'${workDir}/' + headers['zip_entryPath']").autoCreateDirectory(true))
                .get();
    }

    public UnZipTransformer unzipTransformer() {
        UnZipTransformer unzipTransformer = new UnZipTransformer();
        unzipTransformer.setZipResultType(ZipResultType.BYTE_ARRAY);
        return unzipTransformer;
    }

    public UnZipResultSplitter unZipResultSplitter() {
        return new UnZipResultSplitter();
    }

    @Bean
    public MessageChannel zipInboundResultChannel() {
        return MessageChannels.queue("zipInboundResultChannel").get();
    }

    @Bean
    public MessageChannel unzipInboundResultChannel() {
        return MessageChannels.queue("unzipInboundResultChannel").get();
    }

    @Bean
    public IntegrationFlow unzipFlow() {
        return IntegrationFlows.from(zipInboundResultChannel())
                .transform(unzipTransformer())
                .split(unZipResultSplitter(), "splitUnzippedMap")
                .channel(unzipInboundResultChannel())
                .get();
    }
```
The expression using workDir is not being interpreted correctly (it results in a directory named '${workDir}' ) but it also doesn't result in the files being written out to the directory even when I use `new Files('/tmp')` instead (in that case, I just get the zip file itself). Is there anything I'm configuring incorrectly?

**Comment by artembilan** [comment]
Hello @robmoore !

Thank you for the attention to the Framework and such a quick side feedback just after release :smile: .

Anyway let me explain something for your and work out the proper solution, if you really would like to have it in the Java DSL style.

1. The `${workDir}` is a [`PropertyPlaceholder`](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/xsd-configuration.html#xsd-config-body-schemas-context-pphc) notation for the XML bean definition. If you are going to do something similar, you should use `@PropertySource`, `PropertySourcesPlaceholderConfigurer` and `@Value` to get the real value for the `workDir` property, if that.

2. Pay attention to the XML config:
```
directory-expression="'${workDir}/' + headers.zip_entryPath"
```
It is dynamic runtime SpEL, which is evaluated against each request Message. You use there correct factory method to get the `FileWritingMessageHandler`, but your SpEL there is just **literal**.

Should be something like this:
```
@Bean
public IntegrationFlow fileWritingFlow(@Value("workDir") String workDir) {
     return IntegrationFlows.from(unzipInboundResultChannel())
                                  .wireTap(f -> f.handle(logger()))
                                  .handle(Files.outboundAdapter("'" + workDir + "/' + headers['zip_entryPath']")
                                                   .autoCreateDirectory(true))
                                 .get();
}
```
Although, from the Java 8 perspective it would look better:
```
Files.outboundAdapter(m ->  workDir + "/" + m.getHeaders().get(ZipHeaders.ZIP_ENTRY_PATH))
```

Come back, please, if anything isn't clear yet.

**Comment by robmoore** [comment]
Thanks for the quick reply @artembilan. I implemented the handler as you suggested and end up with a null value for the `ZIP_ENTRY_PATH` value (eg, `/tmp/int-zip/null/my.zip`) and still am getting the zip file written out rather than the expanded set of files.

**Comment by artembilan** [comment]
Well, you should share the test case then....
And may some DEBUG logs for the `org.springframework.integration` category to see the picture of the flow.

**Comment by robmoore** [comment]
@artembilan OK, I've got the splitter working and the problem was apparently due to the router configuration (not shown). Sorry for the false alarm and thank you (once again) for your help.
