### ISSUE TITLE
ZipTransformer: "deleteFiles" throwing exception

### ISSUE THREAD

**Issue by muraliyaj** [spring-projects/spring-integration-extensions#164]
Issue: 
`deleteFiles=true` causing below exception .
```
org.zeroturnaround.zip.ZipException: java.io.FileNotFoundException: <Abosulate Path of File with File name>The system cannot find the file specified)
```
Reason:
Inside `ZipTransformer`, `deleteFiles` is used to delete the original file before corresponding `FileSource` is used to compress the file.
That is causing `FileNotFoundException`.

**Comment by artembilan** [comment]
Thank you for reporting this!

Really bug. Confirmed with simple `zipTransformer.setDeleteFiles(true);` modification to the `ZipTransformerTests.zipFile()` test-case.

Will be fixed soon.

**Comment by muraliyaj** [comment]
Thank you Artem.

**Comment by muraliyaj** [comment]
Also, This ZIP transformer may need 'error handling mechanism( like error output channel or hook points to advice chain)' to handle failed compression cases like disk full or issues with output channel.

**Comment by artembilan** [comment]
The error handling isn't `Transfrormer` responsibility. The thrown Exception can be simply `try...catched` by the caller upstream or send to the `errorChannel` in case of async hand off.

In addition, with Java Config the `@Transformer` annotation can be supplied with `adviceChain` where one of that can be `ExpressionEvaluatingRequestHandlerAdvice`.
But, eh, I agree that we have missed `<request-hadnler-advice-chain>` there for the `<int-zip:zip-transformer>`.
Will fix here as well.
