### ISSUE TITLE
integration-zip extension and Spring cloud stream

### ISSUE THREAD

**Issue by jvmlet** [spring-projects/spring-integration-extensions#166]
Hello
Are you going  to expose integration-zip functionalities as spring-cloud-stream zip sink, source and processor ? 
Thanks

**Comment by artembilan** [comment]
No, we aren't. Just because there was no any requirements yet.
As usual: contribution is welcome!

@sabbyanandan , please, help us to evaluate the best place for asking new `spring-cloud-stream-app-starters` and yes, the Contribution Guidelines would be appreciated.

Thank you both!

**Comment by sabbyanandan** [comment]
@artembilan: We have created a release train equivalent repo for "core" backlog items. We could drop an issue [here](https://github.com/spring-cloud-stream-app-starters/app-starters-release-train) for SCStAS tracking.

**Comment by artembilan** [comment]
Thank you @sabbyanandan !

But eh..., not really. The place should be definitely for requesting new applications or common problems.
The GitHub org is ideal, but it doesn't allow to issue requests.

The `app-starters-release-train` is good place for gathering everything together. And yeah, it can be used for scattering as well. Maybe just name doesn't fit? And maybe just for my mind :smile: 

I'd call that project as `app-starters-main` or `app-starters-parent` and let people know that it is a place to request new apps and collect everything as a release train.

But again: it is just IMHO.

@jvmlet , now you know where to go.

When we all evaluate something as `zip` app, we just need to `RELEASE` `spring-integration-zip`.

**Comment by artembilan** [comment]
@jvmlet ,

This is the place where people should request new SCSt App starters: https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues

Closing this as non-relevant.
