### ISSUE TITLE
Maven coordinates

### ISSUE THREAD

**Issue by jvmlet** [spring-projects/spring-integration-extensions#167]
Would you please point me to the maven repository hosting these artifacts ?
Thanks

**Comment by artembilan** [comment]
https://repo.spring.io/libs-snapshot/ is the best place to find all the artifacts produced by Spring IO and even their dependencies.

Since not all modules in this projects has been even reached their Milestone, you should use `BUILD-SNAPSHOT` for them. And that repository contains them.

**Comment by jvmlet** [comment]
Thanks
