### ISSUE TITLE
smb MessageHandler not correctly serializing user/password

### ISSUE THREAD

**Issue by gorille** [spring-projects/spring-integration-extensions#193]
Hi Folks,

I've just tried to use the spring integration smb extension to push files [according to this post](https://spring.io/blog/2017/01/18/spring-integration-extension-for-smb-0-5-0-is-available).

```
@Bean
public MessageHandler smbMessageHandler(SmbSessionFactory smbSessionFactory) {
    FileTransferringMessageHandler<SmbFile> handler =
                new FileTransferringMessageHandler<>(smbSessionFactory);
    handler.setRemoteDirectoryExpression(
                new LiteralExpression("remote-target-dir"));
    handler.setFileNameGenerator(m ->
                m.getHeaders().get(FileHeaders.FILENAME, String.class) + ".test");
    handler.setAutoCreateDirectory(true);
    return handler;
}
```

I do fill in the user/password/doamin and when I launch the code, I get an error 

```
Caused by: org.springframework.core.NestedIOException: Unable to initialize share: smb://user%3Apassword@hostname:445/test-seb; nested exception is jcifs.smb.SmbAuthException: Logon failure: unknown user name or bad password.
```

Please do note the **user%3Apassword** , this comes from [here](https://github.com/spring-projects/spring-integration-extensions/blob/master/spring-integration-smb/src/main/java/org/springframework/integration/smb/session/SmbConfig.java#L173)

`URLEncoder.encode(domainUserPass, "UTF8");` is basically encoding the `:` which is wrong.
correct URL scheme should be smb://user:password@host:445 instead of   smb://user%3Apassword@host:445

**Comment by artembilan** [comment]
Please, share with us how do you configure those `user/password/doamin`.

However It looks like would be better to use `UriComponentsBuilder` from Spring Web for encoding: https://docs.spring.io/spring/docs/5.0.6.RELEASE/spring-framework-reference/web.html#mvc-uri-building

**Comment by gorille** [comment]
I use the provided SmbSessionFactory  as explained in the post.

```
SmbSessionFactory factory = new SmbSessionFactory()
factory.setUsername("user");
factory.setPassword("password");
...
... // and later in the code
FileTransferringMessageHandler<SmbFile> handler = new FileTransferringMessageHandler<> (factory );
