### ISSUE TITLE
Update spring-integration-hazelcast to spring-integration 5.x

### ISSUE THREAD

**Issue by slowjack2k** [spring-projects/spring-integration-extensions#197]
Hi,

at the moment spring-integration-hazelcast does not work with spring integration 5.
For instance `HazelcastMessageStore` does not implement all abstract methods.

Are there any plans for an update?

regards
jack

**Comment by artembilan** [comment]
Good catch, @slowjack2k !

Well, there is no plans, but no one stops us to start a new version `2.0.0` on the matter and upgrade as you mention.

The contribution is welcome!
