### ISSUE TITLE
Update version of dependant library jCIFS to handle SMB2/SMB3

### ISSUE THREAD

**Issue by GregBragg** [spring-projects/spring-integration-extensions#206]
Currently the version of jCIFS used only supports SMB1, need to update the dependant lib to the latest version that handles SMB2/SMB3.

**Comment by artembilan** [comment]
Here is the release BTW: https://spring.io/blog/2019/04/10/spring-integration-smb-1-1-ga-available

**Comment by GregBragg** [comment]
Thanks you very much Artem!

Greg.
