### ISSUE TITLE
spring-integration-smb memory leak in SmbShare

### ISSUE THREAD

**Issue by beardy247** [spring-projects/spring-integration-extensions#225]
Hi,

I've been experiencing a memory leak generated by SmbSession. I wasn't using a CachingSessionFactory so each poll was causing a leak due to the open file blocking the thread from finalizing. I've tracked it down to this method on SmbShare:

```
void doClose() {
    this.open.set(false);
}
```

Looks like the comment is out of date, jcifs.smb.SmbFile close() method is public. Calling super.close() resolves the memory leak. 

Thanks,
Adam

**Comment by artembilan** [comment]
Thank you for reporting this observation! We would appreciate if you raise a pull request with respective fix.
