### ISSUE TITLE
spring-integration-zip: Status?

### ISSUE THREAD

**Issue by mpern** [spring-projects/spring-integration-extensions#245]
Hi all!

What's the status of `spring-integration-zip`?

If I look at the build, it is still compiled against Spring Integration 4.3 which means it is not really compatible against Spring Integration 5.x

Is there a different/better way to handle zip files?

**Comment by artembilan** [comment]
Thank you for raising this concern!

If it is not compatible, then we just need to start a new version, fix and release.
Our point was to keep only one version for all the backward compatibility to minimize support burden for these extension modules.

How does it look from an exception perspective, please, which would make us to bump Spring Integration Core dependency and start a new version for this Zip project?

**Comment by mpern** [comment]
The one problematic bit I know of:

There are is a method signature incompatibility in:

`org.springframework.integration.zip.transformer.AbstractZipTransformer#doTransform` (spring-integration-zip)

```
protected Object doTransform(Message<?> message) throws Exception 
```

vs

`org.springframework.integration.transformer.AbstractTransformer#doTransform` (spring-integration-core)

```
protected abstract Object doTransform(Message<?> message)
```

**Comment by artembilan** [comment]
Yeah... I see your point. 

So, from here we are starting a new version `2.0.0` for this Spring Integration Zip extension and making it based on the latest Spring Integration `5.5`.

We release it probably tomorrow.

Thank you for your patience!

**Comment by artembilan** [comment]
The version `2.0.0` for Spring Integration Zip extension has been released: https://github.com/spring-projects/spring-integration-extensions/commit/9f909c62b296e1139414039832a4b933bcd76c34.

Give it a couple hours to appear in Maven Central.
Although you can use it already from the: https://repo.spring.io/artifactory/release - https://repo.spring.io/artifactory/release/org/springframework/integration/spring-integration-zip/2.0.0/
