### ISSUE TITLE
Doesn't build with Java 17, and old jcifs

### ISSUE THREAD

**Issue by cvetan** [spring-projects/spring-integration-extensions#249]
I have application with Spring Boot 2.5.5, Java 17 and jcifs version 2.1.1 dependency from this library.

The project doesn't build. If I change jcifs version to latest one, then build passes. 

I suppose the dependency listed here needs to be updated.

The exception happening is this: 
```
Caused by: java.lang.IllegalAccessError: failed to access class org.bouncycastle.asn1.DEROutputStream from class jcifs.spnego.NegTokenInit (org.bouncycastle.asn1.DEROutputStream and jcifs.spnego.NegTokenInit are in unnamed module of loader 'app')
```

**Comment by artembilan** [comment]
Feel free to raise a Pull Request with a respective fix.

Although we never advertised to be compatible with Java 17 in this long non updated project, but it doesn't mean that we cannot move on and upgrade it to the latest dependencies and release, respectively.

Thanks
