### ISSUE TITLE
spring-integration-smb not supports Spring 6

### ISSUE THREAD

**Issue by ferblaca** [spring-projects/spring-integration-extensions#261]
From `spring-core` version 6 has removed the `org.springframework.core.NestedIOException` class in favor of using `IOException` directly.

Currently, for the latest published version `1.2.2.RELEASE` of `spring-integration-smb` continues to use the class `org.springframework.core.NestedIOException`. For example in this [line](https://github.com/spring-projects/spring-integration-extensions/blob/e35441024b3b66b2eca5b3189b46f5da34740088/spring-integration-smb/src/main/java/org/springframework/integration/smb/session/SmbShare.java#L101).

Do you expect to get a version of `spring-integration-smb` with Spring 6 compatibility?

**Comment by GregBragg** [comment]
Yes I was aware of that, however this extension project is no longer being maintained as it has been moved to the core project at https://github.com/spring-projects/spring-integration

The fix for the issue you have found is in the core SI repo.

**Comment by GregBragg** [comment]
Specifically here are part of the Spring Integration 6.0 releases:
https://github.com/spring-projects/spring-integration/tree/main/spring-integration-smb/src
