### ISSUE TITLE
Splunk: Real-Time search not working

### ISSUE THREAD

**Issue by zenmoto** [spring-projects/spring-integration-extensions#39]
I've been having trouble getting real-time searches to work- the connector launches correctly but then doesn't output results.  I think that I've chased the problem down to the runQuery method in SplunkDataReader- it launches a search and then waits for the job to end before pulling in events.  Since the real-time search never ends the connector sits and blocks while waiting.

I've tested this by launching a search and then finalizing the job from within the Splunk jobs interface.  As soon as the job is finalized, all data is correctly delivered into the integration pipeline.

**Comment by artembilan** [comment]
Closed in favor of https://jira.springsource.org/browse/INTEXT-72
